const Event = require('../models/Event');

/**
 * @route   POST /api/events
 * @desc    Create a new event
 * @access  Private (organizer only)
 */
const createEvent = async (req, res) => {
  try {
    const { name, venue, date, time, latitude, longitude, geofenceRadius } = req.body;

    // ---------- Input validation ----------
    if (!name || !venue || !date || !time || latitude == null || longitude == null) {
      return res.status(400).json({
        error: 'All fields are required (name, venue, date, time, latitude, longitude)',
      });
    }

    if (typeof latitude !== 'number' || typeof longitude !== 'number') {
      return res.status(400).json({ error: 'Latitude and longitude must be numbers' });
    }

    if (geofenceRadius != null && (typeof geofenceRadius !== 'number' || geofenceRadius <= 0)) {
      return res.status(400).json({ error: 'Geofence radius must be a positive number (in meters)' });
    }

    // ---------- Create event ----------
    const event = await Event.create({
      name,
      venue,
      date,
      time,
      latitude,
      longitude,
      geofenceRadius: geofenceRadius || 100,
      organizer: req.user.id,
      // qrCode is auto-generated by pre-save hook
    });

    res.status(201).json({
      message: 'Event created successfully',
      event,
    });
  } catch (err) {
    console.error('CreateEvent error:', err.message);
    res.status(500).json({ error: 'Server error during event creation' });
  }
};

/**
 * @route   GET /api/events/mine
 * @desc    Get all events created by the logged-in organizer
 * @access  Private (organizer only)
 */
const getMyEvents = async (req, res) => {
  try {
    const events = await Event.find({ organizer: req.user.id }).sort({ date: 1 });

    res.json({ count: events.length, events });
  } catch (err) {
    console.error('GetMyEvents error:', err.message);
    res.status(500).json({ error: 'Server error fetching your events' });
  }
};

/**
 * @route   GET /api/events/upcoming
 * @desc    Get all upcoming events (date >= today) — safe fields only, no qrCode
 * @access  Private (any authenticated user)
 */
const getUpcomingEvents = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const events = await Event.find({ date: { $gte: today } })
      .select('name venue date time geofenceRadius')
      .sort({ date: 1 });

    res.json({ count: events.length, events });
  } catch (err) {
    console.error('GetUpcomingEvents error:', err.message);
    res.status(500).json({ error: 'Server error fetching upcoming events' });
  }
};

/**
 * @route   GET /api/events/:id
 * @desc    Get full event details — organizer sees everything; other users see only upcoming events
 * @access  Private (any authenticated user)
 */
const getEventById = async (req, res) => {
  try {
    const event = await Event.findById(req.params.id).populate('organizer', 'name email');
    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    // Organizer who owns the event can always see full details
    const isOwner = event.organizer._id.toString() === req.user.id;

    if (!isOwner) {
      // Non-owners can only view upcoming events, and without the qrCode
      const today = new Date();
      today.setHours(0, 0, 0, 0);

      if (event.date < today) {
        return res.status(403).json({ error: 'Forbidden — this event is no longer accessible' });
      }

      // Return without qrCode for non-owners
      const { qrCode, ...safeEvent } = event.toObject();
      return res.json({ event: safeEvent });
    }

    res.json({ event });
  } catch (err) {
    console.error('GetEventById error:', err.message);
    res.status(500).json({ error: 'Server error fetching event' });
  }
};

/**
 * @route   PUT /api/events/:id
 * @desc    Update an event (owner organizer only)
 * @access  Private (organizer only)
 */
const updateEvent = async (req, res) => {
  try {
    const event = await Event.findById(req.params.id);
    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    // ---------- Ownership check ----------
    if (event.organizer.toString() !== req.user.id) {
      return res.status(403).json({ error: 'Forbidden — you can only update your own events' });
    }

    // ---------- Allowed fields only ----------
    const allowedUpdates = ['name', 'venue', 'date', 'time', 'latitude', 'longitude', 'geofenceRadius'];
    const updates = {};
    for (const field of allowedUpdates) {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
      }
    }

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({ error: 'No valid fields to update' });
    }

    const updatedEvent = await Event.findByIdAndUpdate(req.params.id, updates, {
      new: true,
      runValidators: true,
    });

    res.json({
      message: 'Event updated successfully',
      event: updatedEvent,
    });
  } catch (err) {
    console.error('UpdateEvent error:', err.message);
    res.status(500).json({ error: 'Server error during event update' });
  }
};

/**
 * @route   DELETE /api/events/:id
 * @desc    Delete an event (owner organizer only)
 * @access  Private (organizer only)
 */
const deleteEvent = async (req, res) => {
  try {
    const event = await Event.findById(req.params.id);
    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    // ---------- Ownership check ----------
    if (event.organizer.toString() !== req.user.id) {
      return res.status(403).json({ error: 'Forbidden — you can only delete your own events' });
    }

    await Event.findByIdAndDelete(req.params.id);

    res.json({ message: 'Event deleted successfully' });
  } catch (err) {
    console.error('DeleteEvent error:', err.message);
    res.status(500).json({ error: 'Server error during event deletion' });
  }
};

module.exports = { createEvent, getMyEvents, getUpcomingEvents, getEventById, updateEvent, deleteEvent };
